### ISSUE TITLE
Dot product incorrect for some instances

### ISSUE THREAD

**Issue by lunelis** [tanguyl/numerl#16] opened 2023-04-12 17:12 UTC
Hello,
I have been using the library for my master thesis and found a bug.
When doing the following computations : 
```
C = numerl:matrix([[1,2], [3,4]]),
D = numerl:matrix([[5], [6]]),
R = numerl:dot(C,D).
```
R is equal to [[5],[15]] when it should be equal to [[17],[39]]

The following computations also end up in an error:
```
E = numerl:matrix([[1,2]]),
F = numerl:matrix([[3], [4]]),
T = numerl:dot(E,F).
```
T is equal to [[3]] when it should be equal to [[11]].
It looks like it only considers the first integer and not the second in the dot product.
It seems that the bug occurs when dealing with matrices of different sizes and here if the second matrix is of size 1*n.

I tried to dig into the code but couldn't find where this was coming from. I guess that it doesn't come from the cblas library so I suspect that it is coming from the binary representation being incorrect but I couldn't spot the problem.

What do you think about it ? Do you have any time to look at that issue ?

Thank you in advance for your help.
Lucas Nélis

**Comment by tanguyl** [comment] 2023-04-12 18:15
Hello,

This bug is now corrected; sorry you had to experience it. 
The issue was actually linked to cblas; I fucked up the LDB parameter of DGEMM.
Is the fix working on your side?

Would you also tell me your master thesis name? This library only utility so far have been writing bad tests; I'd be curious to see an actual use case. 

Kind regards,
Tanguy Losseau

**Comment by lunelis** [comment] 2023-04-13 08:08
Hello,
Thanks for your quick reaction ! The bug seems to be fixed. I was not sure what the LDA and LDB parameters were used for.

My master thesis is "Low-cost high speed sensor fusion with Hera and Grisp". I have to improve the speed of the Hera framework by porting it to a new version of the Grisp board and improving the matrix computations which were up to now done in pure Erlang. Using your library should speed up these computations by a factor of 10. We will see if that is the case but I hope so !

I have seen that you recommand using the equals function of your library to compare the matrices. Why is that the case ? I have observed that the result of the == operator can vary. 

Kind regards,
Lucas Nélis

**Comment by tanguyl** [comment] 2023-04-13 09:49
Hello again,

That sounds a lot of fun. Did you have any issues linking openblas for Grisp?

As for the whole '==' varying results, floating points number have a finite precision, which can quickly lead to approximation errors (ex: https://stackoverflow.com/questions/4915462/how-should-i-do-floating-point-comparison). The "equals" function numerl provides checks equality down to 1e-6 if I recall correctly to provide less accurate (and hence, ironically, more accurate) comparison.

**Comment by lunelis** [comment] 2023-04-13 12:01
I haven't run it on Grisp yet. Reading your implementation remembered me of that floating point problem ! I'm trying to test it as much as possible before running it on Grisp and I stumbled upon a weird behavior when repeating the following test : 
```
C = numerl:matrix([[1,2], [3,4]]),
D = numerl:matrix([[5,6], [7,8]]),
R = numerl:mtfli(numerl:dot(C,D)).
```
R can be equal to [[19,22], [43,50]] which is correct. But sometimes my test fails and R is equal to [[19,22], [43,56]] or [[19,22], [43,-2147483648]]. Some of my other tests also fail periodically but that one seems to fail quite often.
The last number is always the one changing. Again I tried to look in the source code but couldn't find the problem.

Thanks for your time and help !

**Comment by petervanroy** [comment] 2023-04-13 12:52
Hi all,

The occurrence of -2147483648 (2^31, 2's complement) seems to indicate 
that the problem is due to a type mismatch.  A parameter of type "int" 
is sometimes read as "long int", 64 bit instead of 32 bit, and the extra 
32 bits give a problem if they are not 0.

Peter

**Comment by tanguyl** [comment] 2023-04-13 13:52
Hello,

I made a typo; dgemm calculates alpha*A*B + beta*C. I wrote beta=0, but passed the value 1 in the dgemm call. Since matrix C is only allocated (and not initialized), a touch of randomness happened.
I pushed a fix. Please do tell me if it works for you too, and do not hesitate to send me back any other failures observed on this library.

It is not impossible I made mistakes in types mismatch either, which could explain additional random bug you might still encounter.

I apology for these errors; and hope you can proceed to your work without additional bugs.
Tanguy

**Comment by lunelis** [comment] 2023-04-13 14:41
Hello,

It is working fine for repeated tests. I will keep you updated if I encounter other bugs. I finished replacing the matrix library and didn't find any other bug for the moment.

Thanks for your quick help.
Lucas

**Closed as completed** 2023-04-13 14:50 UTC
